// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGM1_PUSCMnknt1rj8dA5XFvhbSjBxsbM',
    appId: '1:1035182894108:android:3362b0832fcf75d1dc03d9',
    messagingSenderId: '1035182894108',
    projectId: 'ecom-app-bed72',
    storageBucket: 'ecom-app-bed72.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyl4W9MQEKCiZcRFN2nL7frsoz58pqA0',
    appId: '1:1035182894108:web:f45570a32d793bb3dc03d9',
    messagingSenderId: '1035182894108',
    projectId: 'ecom-app-bed72',
    authDomain: 'ecom-app-bed72.firebaseapp.com',
    storageBucket: 'ecom-app-bed72.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgHxWYzsV_6VdLCIxfGG56uQaWCTsaw8',
    appId: '1:1035182894108:ios:ed7ef198ba96eeaddc03d9',
    messagingSenderId: '1035182894108',
    projectId: 'ecom-app-bed72',
    storageBucket: 'ecom-app-bed72.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgHxWYzsV_6VdLCIxfGG56uQaWCTsaw8',
    appId: '1:1035182894108:ios:ed7ef198ba96eeaddc03d9',
    messagingSenderId: '1035182894108',
    projectId: 'ecom-app-bed72',
    storageBucket: 'ecom-app-bed72.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyl4W9MQEKCiZcRFN2nL7frsoz58pqA0',
    appId: '1:1035182894108:web:f465c280ef9bd8d2dc03d9',
    messagingSenderId: '1035182894108',
    projectId: 'ecom-app-bed72',
    authDomain: 'ecom-app-bed72.firebaseapp.com',
    storageBucket: 'ecom-app-bed72.firebasestorage.app',
  );

}